POST http://localhost:8080/events
content-type: : application/json
Authorization: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q1QGVtYWlsLmNvbSIsImV4cCI6MTcxMTgyNzI3NiwidXNlcklkIjoxfQ.4SH-F9a7VEQiJoUcJyAE39hsDZvNYFcahq7AudwVwbbMEZaPZuY7Ek0_zy3yxV5mutOYP_7R7R9Mma9haIf-5A

{
    "name": "Test event",
    "description": "A Test event",
    "location": "Event location",
    "dateTime": "2025-02-02T15:30:00.000Z"
}